Added config for terminator
git-svn-id: https://roboticssrv.wtb.tue.nl/svn/ros/tue_env@28271 3a3c2cfb-d3b9-409e-9e75-db8fcdbcaac6

diff --git a/installer/scripts/tue-install-impl b/installer/scripts/tue-install-impl
--- a/installer/scripts/tue-install-impl
+++ b/installer/scripts/tue-install-impl
@@ -292,6 +292,52 @@ function tue-install-cp
 
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
 
+# Reads SOURCE_FILE and looks in TARGET_FILE for the first and last line of SOURCE_FILE. If these
+# are not found, SOURCE_FILE is appended to TARGET_FILE. Otherwise, the appearance of the first and
+# last line of SOURCE_FILE in TARGET_FILE, and everything in between, is replaced by the contents
+# of SOURCE_FILE.
+# This is useful for adding text blocks to files and allowing to change only that part of the file
+# on a next update. It is advised to start and end SOURCE_FILE with unique tags, e.g.:
+#
+#    # BEGIN TU/E BLOCK
+#    .... some text ...
+#    # END TU/E BLOCK
+#
+function tue-install-add-text
+{
+    if [ -z "$2" ]
+    then
+        tue-install-error "Invalid tue-install-add-text call. Usage: tue-install-add-text SOURCE_FILE TARGET_FILE"
+    fi
+
+    local source_file=$TUE_INSTALL_CURRENT_TARGET_DIR/$1
+    local target_file=$2
+
+    if [ ! -f $source_file ]
+    then
+        tue-install-error "tue-install-add-text: No such file: $source_file"
+    fi
+
+    if [ ! -f $target_file ]
+    then
+        tue-install-error "tue-install-add-text: No such file: $target_file"
+    fi
+
+    local begin_tag=$(head -n 1 $source_file)
+    local end_tag=$(tail -n 1 $source_file)
+    local text=$(cat $source_file)
+
+    if ! grep -q "$begin_tag" $target_file
+    then
+        echo -e "$text" >> $target_file
+    else
+        sed -e "/^$end_tag/r $source_file" -e "/^$begin_tag/,/^$end_tag/d" $target_file > $target_file.tmp
+        mv $target_file.tmp $target_file
+    fi
+}
+
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
+
 function tue-install-system
 {
     if [ -z "$1" ]
