Nobleo-backport
With:
Support for branches: Usefull for CI
More robust package installing options
Install snapd if using snaps
Activate docker permissions on install
Install less packages initially when installing ROS

diff --git a/installer/scripts/tue-install-impl b/installer/scripts/tue-install-impl
--- a/installer/scripts/tue-install-impl
+++ b/installer/scripts/tue-install-impl
@@ -18,7 +18,7 @@ function _make_sure_installed
     local pkgs_to_install=
     for pkg in $@
     do
-        if ! dpkg -s $pkg &> /dev/null
+        if ! dpkg-query -W -f='${Status}' $pkg 2>/dev/null | grep -q "ok installed" #Handles uninstalled packages
         then
             pkgs_to_install="$pkgs_to_install $pkg"
         fi
@@ -223,7 +223,25 @@ function tue-install-git
             cres=
         fi
 
-        res=$res$cres
+        res="$res $cres"
+        cd $mem_pwd
+    fi
+
+    if [ -n "$BRANCH" ]; #Cannot be combined with version-if because this one might not exist
+    then
+        mem_pwd=$PWD
+        cd $2
+
+        tue-install-debug "cd $2 && git checkout $BRANCH"
+
+        cres=$(git checkout $BRANCH 2>&1)
+        tue-install-debug "$cres"
+        if [[ $cres == "Already on "* || $cres == "error: pathspec"* ]]
+        then
+            cres=
+        fi
+
+        res="$res $cres"
         cd $mem_pwd
     fi
 
@@ -363,6 +381,35 @@ function tue-install-system
     TUE_INSTALL_SYSTEMS="$1 $TUE_INSTALL_SYSTEMS"
 }
 
+function tue-install-system-now
+{
+    tue-install-debug "tue-install-system-now $@"
+    if [ -z "$1" ]
+    then
+        tue-install-error "Invalid tue-install-system-now call: needs package as argument."
+    fi
+    local install_required=false
+
+    for pkg in "$@"
+    do
+        # Check if pkg is not already installed dpkg -S does not cover previously removed packages
+        # Based on https://stackoverflow.com/questions/1298066
+        if ! dpkg-query -W -f='${Status}' $pkg 2>/dev/null | grep -q "ok installed"
+        then
+            tue-install-debug "Package $pkg requires installation"
+            install_required=true
+        else
+            tue-install-debug "Package $pkg is already installed"
+        fi
+    done
+
+    if $install_required
+    then
+        echo "sudo apt-get install --assume-yes $@"
+        sudo apt-get install --assume-yes $@
+    fi
+}
+
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 
 function tue-install-ppa
@@ -495,8 +542,8 @@ function tue-install-ros {
 
         if  [ -f $ros_pkg_dir/package.xml ]; then
             # Catkin
-
             deps=`$TUE_INSTALL_SCRIPTS_DIR/parse-ros-package-deps $ros_pkg_dir/package.xml`
+            tue-install-debug "Parsed package.xml \n $deps"
 
             for dep in $deps
             do
@@ -624,7 +671,7 @@ do
     if [ -d $TUE_INSTALL_TARGET_DIR/$target ]
     then
         # Mark as installed
-	tue-install-debug "[$target] marked as installed after a successful install"
+        tue-install-debug "[$target] marked as installed after a successful install"
         touch $TUE_INSTALL_INSTALLED_DIR/$target
     fi
 done
@@ -731,6 +778,8 @@ fi
 if [ -n "$TUE_INSTALL_SNAPS" ]; then
 
     TUE_INSTALL_CURRENT_TARGET="SNAP"
+
+    _make_sure_installed snapd
 
     echo -e "\nyes | sudo snap install --classic $TUE_INSTALL_SNAPS" >> $INSTALL_DETAILS_FILE
 
